#! /bin/bash

# Update 
yes | pacman -Syuu

# Install command-line tools to download stuff.

yes | pacman -Syyu git wget curl

# Install AUR helper. I personally use Paru.
# This assumes you've got base base-devel pkg installed. If not install it.

cd ~/
git clone https://aur.archlinux.org/paru.git
cd paru
makepkg -si
cd ..

# Install and config wm env stuff

yes | pacman -Syyu xorg
yes | pacman -Syyu lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings

# Node js and python envs

cd ~/ 
mkdir .local/npm 
mkdir .local/python
mkdir .local/python/bin

# Create python env

python3 -m venv /home/prxvvy/.local/python/bin

# Install dev stuff.

yes | pacman -Syyu nodejs npm # nodejs
yes | pacman -Syyu python python-pip # Python and pip
yes | pacman -Syyu gcc clang valgrind gdb ninja cmake make # C stuff
yes | pacman -Syyu neovim
yes | pacman -Syyu zip
yes | pacman -Syyu unzip
yes | pacman -Syyu unrar
yes | pacman -Syyu tar
yes | pacman -Syyu tmux

systemctl enable lightdm.service # Enable display manager so that we can login with it in next reboot.

# Install my .dotfiles

# Install dwm

cd ~/ 
git clone https://github.com/prxvvy/.dotfiles
cd .dotfiles
cd dwm
make install clean 
cd..

# Install st 

cd st
make install clean
cd ..

# Install dmenu

cd dmenu
make install clean
cd ..

# Install dwmblocks 
cd dwmblocks
make install clean 
cd ..

# Install zsh

yes | pacman -Syyu zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Linking stuff from .dotfiles

cd ~/ 
# Link neovim configs
ln -s /home/prxvvy/.dotfiles/nvim/ /home/prxvvy/.config
# Link some scripts
ln -s /home/prxvvy/.dotfiles/scripts/ /home/prxvvy/.config
# Link npmjs env so that we don't have to run npm install with sudo
ln -s /home/prxvvy/.dotfiles/.npmrc /home/prxvvy/
# Link .zshrc
ln -s /home/prxvvy/.dotfiles/zsh/.zshrc /home/prxvvy/
# Link .profile
ln -s /home/prxvvy/.dotfiles/.profile /home/prxvvy

# Install fonts

cd ~/ 

# Hack Nerd Font

mkdir Hack
wget https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip
unzip Hack.zip
mv *ttf Hack

rm Hack.zip

# JetBrainsMono 

mkdir JetBrainsMono
wget https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/JetBrainsMono.zip
unzip JetBrainsMono.zip
mv *.ttf JetBrainsMono
rm JetBrainsMono.zip

mv JetBrainsMono Hack /usr/local/share/fonts

# Install misc stuff

paru -Syyu brave-bin
yes | pacman -Syyu thunar

# automount devices and partitions. In my case helpful if I wanna mount my windows parition

yes | pacman -Syyu gvfs
yes | pacman -Syyu gvfs-afc
yes | pacman -Syyu gvfs-gphoto2
yes | pacman -Syyu gvfs-mtp
yes | pacman -Syyu gvfs-nfs
yes | pacman -Syyu gvfs-smb
yes | pacman -Syyu mtpfs
yes | pacman -Syyu udiskie
yes | pacman -Syyu udisks2

cd ~/

mkdir workspace

# Python stuff

pip install pynvim
pip install black

# npm pkgs
npm install -g typescript
npm install -g prettier

reboot
