#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom -f &
feh --bg-fill $HOME/.dotfiles/wallpapers/"gruv-simplistic-ngo".png
xset s off && xset -dpms
/home/prxvvy/.config/polybar/launch.sh
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
 
dunst -conf $HOME/.config/dunst/dunstrc &

bspc monitor -d    

bspc config normal_border_color     '#D3869B'
bspc config active_border_color     '#83A598'
bspc config focused_border_color    '#83A598'
bspc config top_padding         50
bspc config border_width         3
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
