#!/bin/bash

WIFINAME="$(nmcli -t -f name connection show --active)"
INTERFACE="wlp0s20f3"
WIFISYMBOL="$INTERFACE: $WIFINAME"

if [[ $WIFINAME == "" ]]; then
	WIFISYMBOL="$INTERFACE: Not connected"
fi

# echo "  $INTERFACE: $WIFINAME"
echo "$WIFISYMBOL"
