#!/bin/bash

INTERFACE="wlp0s20f3"
READER="/usr/bin/cat"
PURPLE="#d3869b"
 
R1=`$READER /sys/class/net/$INTERFACE/statistics/rx_bytes`
T1=`$READER /sys/class/net/$INTERFACE/statistics/tx_bytes`
R2=`$READER /sys/class/net/$INTERFACE/statistics/rx_bytes`
T2=`$READER /sys/class/net/$INTERFACE/statistics/tx_bytes`
TBPS=`expr $T2 - $T1`
RBPS=`expr $R2 - $R1`
TKBPS=`expr $TBPS / 1024`
RKBPS=`expr $RBPS / 1024`


TKBPS=`expr $TBPS / 1024`
RKBPS=`expr $RBPS / 1024`

arrow_down=""
arrow_up=""

echo "^c$PURPLE^$icon" "$RKBPS kb" "$arrow_down $arrow_up" "$TKBPS kb"
