#!/bin/bash

WIFINAME="$(nmcli -t -f name connection show --active)"
INTERFACE="wlp0s20f3"
ICON=""
WIFISYMBOL="$ICON  $WIFINAME"

if [[ $WIFINAME == "" ]]; then
	WIFISYMBOL="$ICON! Not connected"
fi

# echo "  $INTERFACE: $WIFINAME"
echo "$WIFISYMBOL"
